### ISSUE TITLE
Using with a crate that uses proc_macro

### ISSUE THREAD

**Issue by Thinkofname** [japaric/xargo#125]
e.g. serde

I've tried a few different ways to get this to work but it always ends up with 
```
error: libproc_macro.so: cannot open shared object file: No such file or directory
  --> src/lib.rs:23:1
   |
23 | extern crate serde_derive;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Not sure if i'm missing something

**Comment by japaric** [comment]
Could you provide more details? Are you cross compiling or compiling natively? Have you tried listing `proc_macro` as a dependency in Xargo.toml?

**Comment by Thinkofname** [comment]
Native and I had this toml (Term seems to be required for proc_macro to build)
```toml
[target.x86_64-unknown-linux-gnu.dependencies.std]
features = ["jemalloc", "panic_unwind"]
stage = 0

[target.x86_64-unknown-linux-gnu.dependencies.term]
stage = 1

[target.x86_64-unknown-linux-gnu.dependencies.proc_macro]
stage = 2
```
Tried again after removing .Xargo and running `cargo clean` on a newer nightly and it seems to work. Sorry about that
