### ISSUE TITLE
Unable to build simple rustls example (rayon-core can't find panic_unwind)

### ISSUE THREAD

**Issue by johnthagen** [japaric/xargo#181]
I am unable to build a simple `rustls` example using Xargo. Details below:

```
$ rustup show
...
active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.24.0-nightly (cfba0d446 2017-12-05)

$ xargo --version
xargo 0.3.8
cargo 0.24.0-nightly (5bb478a51 2017-11-29)
```

```toml
# Xargo.toml
[dependencies.std]
features = ["force_alloc_system"]
```

```toml
# Cargo.toml
[package]
name = "rustls-test"
version = "0.1.0"

[dependencies]
rustls = "0.11.0"

[profile.release]
panic = 'abort'
```

```rust
// main.rs
extern crate rustls;

fn main() {
    println!("Hello, World");
}
```

```
$ xargo build --release
...
error[E0463]: can't find crate for `panic_unwind`
error: aborting due to previous error
error: Could not compile `rayon-core`.
```

Is there a way to solve this issue?
