### ISSUE TITLE
cargo-features = ["strip"] cause compile error

### ISSUE THREAD

**Issue by Frago9876543210** [japaric/xargo#295]
I'm trying to use xargo to reduce space of binary file. [min-sized-rust mentions it here](https://github.com/johnthagen/min-sized-rust#optimize-libstd-with-xargo). But `cargo-features = ["strip"]` cause error.
This thing was recently added (see https://github.com/rust-lang/cargo/issues/3483).

```bash
$ RUST_BACKTRACE=1 xargo build --target x86_64-unknown-linux-gnu --release --verbose

# output:
+ "rustc" "--print" "sysroot"
+ RUSTFLAGS="--sysroot /home/alex/.xargo/HOST -Z force-unstable-if-unmarked"
+ "cargo" "build" "--release" "--manifest-path" "/tmp/xargo.Dax5TY8K3VlJ/Cargo.toml" "--target" "x86_64-unknown-linux-gnu" "-v" "-p" "std"
error: failed to parse manifest at `/tmp/xargo.Dax5TY8K3VlJ/Cargo.toml`

Caused by:
  feature `strip` is required

consider adding `cargo-features = ["strip"]` to the manifest
error: `"cargo" "build" "--release" "--manifest-path" "/tmp/xargo.Dax5TY8K3VlJ/Cargo.toml" "--target" "x86_64-unknown-linux-gnu" "-v" "-p" "std"` failed with exit code: Some(101)
   0: error_chain::make_backtrace
   1: <error_chain::State as core::default::Default>::default
   2: <std::process::Command as xargo::extensions::CommandExt>::run
   3: xargo::sysroot::build
   4: xargo::sysroot::update
   5: xargo::main_inner
   6: std::rt::lang_start::{{closure}}
   7: std::rt::lang_start_internal::{{closure}}
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:297
      std::panicking::try
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/rt.rs:51
   8: main
   9: __libc_start_main
  10: _start

```

Example `Cargo.toml`:
```toml
cargo-features = ["strip"]

[package]
name = "failed_case"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
strip = "symbols"
```
and `Xargo.toml`:
```toml
[dependencies.std]
default-features = false
features = ["panic_unwind"]
```
