### ISSUE TITLE
error[E0463]: can't find crate for `std`

### ISSUE THREAD

**Issue by LoganDark** [japaric/xargo#319]
`Cargo.toml`:

```toml
[package]
name = 'xargo-test'
version = "0.1.0"
edition = "2018"

[dependencies]

[profile.release]
panic = 'abort'
lto = true
codegen-units = 1
incremental = false
opt-level = 'z'
```

`Xargo.toml` per [this issue comment](https://github.com/avr-rust/blink/issues/13#issuecomment-496024900):

```toml
[dependencies.core]
stage = 0

[dependencies.compiler_builtins]
stage = 1
version = '=0.1.47'
```

Builting on WSL 1 Ubuntu 20.04 with a nightly toolchain `nightly-x86_64-unknown-linux-gnu`, `rustc 1.56.0-nightly (d9aa28767 2021-07-24)`.

Man I'm just trying to compile a hello world what is going on...

```
0 logandark ~/h/rust xargo build --release
warning: Patch `rustc-std-workspace-alloc v1.99.0 (/home/logandark/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-alloc)` was not used in the crate graph.
Patch `rustc-std-workspace-core v1.99.0 (/home/logandark/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)` was not used in the crate graph.
Patch `rustc-std-workspace-std v1.99.0 (/home/logandark/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-std)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
   Compiling core v0.0.0 (/home/logandark/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
    Finished release [optimized] target(s) in 9.15s
warning: Patch `rustc-std-workspace-alloc v1.99.0 (/home/logandark/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-alloc)` was not used in the crate graph.
Patch `rustc-std-workspace-core v1.99.0 (/home/logandark/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)` was not used in the crate graph.
Patch `rustc-std-workspace-std v1.99.0 (/home/logandark/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-std)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
  Downloaded compiler_builtins v0.1.47
  Downloaded 1 crate (159.1 KB) in 0.44s
   Compiling compiler_builtins v0.1.47
    Finished release [optimized] target(s) in 2.24s
   Compiling xargo-test v0.1.0 (/home/logandark/xargo-test)
error[E0463]: can't find crate for `std`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `xargo-test` due to previous error
```

**Comment by LoganDark** [comment]
Apparently you have to manually add `std` to the `Xargo.toml` (it is never specified how to do this, but I figured it out):

```toml
[dependencies.core]
stage = 0

[dependencies.compiler_builtins]
stage = 1
version = '=0.1.47'

[dependencies.std]
stage = 2
```
