### ISSUE TITLE
Cross compile std

### ISSUE THREAD

**Issue by japaric** [japaric/xargo#77]
For starters, with a few restrictions
- Xargo won't compile std for the host
- No custom std source
- The Cargo features of `std` can't be tweaked

These issues need to be addressed in rust-lang/rust:
- rust-lang/rust#37252
- rust-lang/rust#36501

But there are probably others. The easiest way to test this feature today is by compiling a binary Cargo project with the following Cargo.toml.

``` toml
[dependencies]
std = "$(rustc --print sysroot)/lib/rustlib/src/rust/src/libstd"
```
