### ISSUE TITLE
Customization of std

### ISSUE THREAD

**Issue by japaric** [japaric/xargo#98]
Once #77 is implemented, people are going to ask for a way to customize the std crate (jemalloc vs alloc_system, backtrace or not, etc.).

So, I have been thinking about how to present "customizability" to users and how to solve the problem of nasty build errors, like libc, that are not actual errors.

My idea is to, by default, only build the `core` crate and have users specify what other dependencies they want + how to customize them via a Xargo.toml file in the root of the Cargo project.

Syntax is undecided but maybe something that looks like Cargo.toml:

``` toml
# Xargo.toml
[dependencies]
collections = "0"  # NOTE version doesn't actually matter

[dependencies.compiler-builtins]
features = ["mem"]
version = "0"
```
